In [4]:
import requests
import pandas as pd

input_text = '''
Am Tue, 16. 05. 22 10:53:31 +0100 schrieb Herbert Auer:


"Fußball ist wie Schach, nur ohne Würfel" (Theodor Fähling)

Größe,

Herbert
'''

url = "http://pseugc-app.project.ris.bht-berlin.de/predict"
payload = {
    "input_texts": [input_text],
    "repeat": 1
}
response = requests.post(url, json=payload)

# print("Status Code:", response.status_code)
# print("Response Body:", response.json())


display(pd.DataFrame(response.json()['output'][0][0]['output_dict']))
print(response.json()['output'][0][0]['output_text'])

  Token_ID   Label  Start  End       Token   Pseudonym
0       T1    DATE      9   19  16. 05. 22  20. 07. 20
1       T2    MALE     43   50     Herbert      Sascha
2       T3  FAMILY     51   55        Auer       Egger
3       T4    MALE    102  109     Theodor    Fridolin
4       T5  FAMILY    110  117     Fähling    Bösching
5       T6    MALE    128  135     Herbert      Sascha

Am Tue, 20. 07. 20 10:53:31 +0100 schrieb Sascha Egger:


"Fußball ist wie Schach, nur ohne Würfel" (Fridolin Bösching)

Größe,

Sascha